# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Guji' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Guji
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'Guji-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GujiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Guji-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Guji-tvOS

  target 'Guji-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
